### ISSUE TITLE
Whenever a lengthy message is returned, the UI updates become increasingly sluggish.

### ISSUE THREAD

**Issue by xuebusi** [alfianlosari/ChatGPTSwiftUI#11]
Whenever a lengthy message is returned, the UI updates become increasingly sluggish, leading to an unpleasant user experience. As a novice, I have been unable to determine the root cause of this problem and would greatly appreciate your assistance in resolving it.

**Comment by alfianlosari** [comment]
Hi, thanks for reporting. I was able to reproduct this and find the root cause. Everytime message row is updated with text, the entire ContentView got recomputed. 

I've found the solution to fix this and plan to create a video for it as well as adding ability to stop streaming response using Task Cancellation!
